name: Release Builds

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: Override version string for manual runs (defaults to ref name)
        required: false

permissions:
  contents: write

jobs:
  build-intel:
    name: Intel macOS (x86_64)
    runs-on: macos-13
    env:
      ARCH: x86_64
    steps:
      - uses: actions/checkout@v4

      - name: Determine version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.version }}" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF_NAME#v}"
          fi
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Build release archive
        run: Scripts/package_app.sh --arch "$ARCH" --version "$VERSION"

      - name: Upload archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: DrawingPad-${{ env.VERSION }}-${{ env.ARCH }}
          path: dist/DrawingPad-${{ env.VERSION }}-${{ env.ARCH }}.zip

      - name: Publish GitHub release asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/DrawingPad-${{ env.VERSION }}-${{ env.ARCH }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}

  build-apple-silicon:
    name: Apple Silicon macOS (arm64)
    runs-on: macos-14
    env:
      ARCH: arm64
    steps:
      - uses: actions/checkout@v4

      - name: Determine version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.version }}" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF_NAME#v}"
          fi
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Build release archive
        run: Scripts/package_app.sh --arch "$ARCH" --version "$VERSION"

      - name: Upload archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: DrawingPad-${{ env.VERSION }}-${{ env.ARCH }}
          path: dist/DrawingPad-${{ env.VERSION }}-${{ env.ARCH }}.zip

      - name: Publish GitHub release asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/DrawingPad-${{ env.VERSION }}-${{ env.ARCH }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
